# Production context:
# All deploys from the main repository branch
# will inherit these settings.
[context.production]
  command = "yarn build"
  [context.production.environment]
    GATSBY_WEATHER_API_KEY = "832138963ce340db8c4941827446f336"
